[package]
name = "scone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
saunter = "0.1.3"
scone_ecs = { path = "../scone_ecs" }
winit = "0.27.5"
